// <auto-generated />
using System;
using AppEvenimente.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppEvenimente.Migrations
{
    [DbContext(typeof(AppEventContext))]
    partial class AppEventContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AppEvenimente.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locatie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeEveniment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Evenimente");
                });

            modelBuilder.Entity("AppEvenimente.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EvenimentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeParticipant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EvenimentId");

                    b.ToTable("Participanti");
                });

            modelBuilder.Entity("AppEvenimente.Models.Participant", b =>
                {
                    b.HasOne("AppEvenimente.Models.Event", "Eveniment")
                        .WithMany("Participanti")
                        .HasForeignKey("EvenimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eveniment");
                });

            modelBuilder.Entity("AppEvenimente.Models.Event", b =>
                {
                    b.Navigation("Participanti");
                });
#pragma warning restore 612, 618
        }
    }
}
