// <auto-generated />
using System;
using AppEvenimente.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppEvenimente.Migrations
{
    [DbContext(typeof(EventContext))]
    partial class EventContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AppEvenimente.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEveniment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locatie")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeEveniment")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Evenimente");
                });

            modelBuilder.Entity("AppEvenimente.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("EvenimentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeParticipant")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Participanti");
                });

            modelBuilder.Entity("AppEvenimente.Models.Participant", b =>
                {
                    b.HasOne("AppEvenimente.Models.Event", "Event")
                        .WithMany("Participanti")
                        .HasForeignKey("EventId");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("AppEvenimente.Models.Event", b =>
                {
                    b.Navigation("Participanti");
                });
#pragma warning restore 612, 618
        }
    }
}
